//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> id_goods_category { get; set; }
        public Nullable<int> id_subsidiary_companies_region { get; set; }
        public Nullable<int> shelf_life { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string code { get; set; }
        public string status { get; set; }
    
        public virtual Subsidiary_companies_region Subsidiary_companies_region { get; set; }
        public virtual Goods_category Goods_category { get; set; }
    }
}
